env:
  node: true
  es2021: true
  jest/globals: true
extends: standard
plugins:
  - jest
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  semi:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
