version: '3.9'

services:
  mysql:
    image: mariadb:10.8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=main
      - LANG=C.UTF-8
    healthcheck:
      test: 'mysqladmin ping -h 127.0.0.1 --port 3306 -u root --password=$$MYSQL_ROOT_PASSWORD'
      interval: 1s
      timeout: 30s
      retries: 30
    volumes:
      - ../test/db:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    tmpfs:
      - /var/lib/mysql
